### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by bialesdaniel**
I checked the docker image to install the packages the same way that the build pipeline is installing the packages. I also added a step to copy the current directory into the docker image. That will help with local development. If this gets approved I will update the documentation here: https://github.com/cmu-db/terrier/wiki/Docker

### CODE REVIEW

**Review by skyfishjy — APPROVED** [review]
LGTM

**Comment by bialesdaniel** [comment]
@skyfishjy Did you happen to try building and running terrier with this docker image? I just want to make sure I don't have something funny on my machine that makes it work.

**Review by benliangw — APPROVED** [review]
I tried it on the testing server.

**Comment by bialesdaniel** [comment]
I'm gonna close this because it was merged into Terrier

**Pull request closed without merging**
